language: node_js
deploy:
  api_key:
    secure: PPwAL5mzU4a+NqsDxhuLnMbipRfpJB9cLW/TqVqFoGjJE1YyJpPF7FwccFxX+1S2jpWIdGp5jomI/DYgMFybV1FGLQlIbvzD5wq1VnKtvE+jZd8sjGhlFgdg9IpZrjzGubrmXzuyKsx/MAl+REaAcNpQpcHkArkuFkD4hmr58W4=
  provider: npm
  email: john@mclear.co.uk
